version: 0.2
phases:
  install:
    commands:
      - sudo pip install -r requirements.txt
      - pip install -U -e ${CODEBUILD_SRC_DIR_infra}
      - python infrastructure.py > template.json
artifacts:
  type: zip
  files:
    - template.json
